### ISSUE TITLE
Some bugs we found from initial testing

### ISSUE THREAD

**Issue by zach333** [p2sr/GhostServer#1]
- Attempting to connect to server while server is not running outputs message "0 ! GO !"
- _sar_ghost_type_ command does not work unless entered while already in server
- Server host has to join the map first, if not then other players can see the host but the host will see the player names and models stuck at position 0 0 0
- Typing _sar_ghost_type_ outputs message "Adjust the tickrate."
- If a player's game crashes, the console gets spammed with "Player (name) has joined map "
- Changing model to anything other than the default can will crash the game of everyone in the server

Also some features that me, ales and Xinera thought would be cool:
- Output in chat "(name) has finished (map) in (time)" when someone completes a map
- Ability to hide names for hide and seek/prop hunt (currently must be done with _sar_ghost_name ""_)

That is all I can remember from our testing. This is really cool Blender and we really enjoyed playing with it. :)

**Comment by Blenderiste09** [comment]
* ~Attempting to connect to server while server is not running outputs message "0 ! GO !"~ : **Fixed**
* ~_sar_ghost_type_ command does not work unless entered while already in server !~ : **Fixed**
 * Server host has to join the map first, if not then other players can see the host but the host will see the player names and models stuck at position 0 0 0
 * ~Typing _sar_ghost_type_ outputs message "Adjust the tickrate."~ : **Fixed**
 * If a player's game crashes, the console gets spammed with "Player (name) has joined map "
* ~Changing model to anything other than the default can will crash the game of everyone in the server~ : **Fixed**

Also some features that me, ales and Xinera thought would be cool:
 
* Output in chat "(name) has finished (map) in (time)" when someone completes a map
* ~Ability to hide names for hide and seek/prop hunt (currently must be done with _sar_ghost_name ""_)~ : Already possible using ***sar_hud_ghost_show_name 0***

Unfortunately, after more testing, it looks like :
- Some people can't receive UDP packets, leading in a bug where they only can see messages and not the ghost (ghost is stuck in 0 0 0)
- Alt-Tabbing might make the game crash
- I'm dumb

So, I'll try to figure what can I do for these cases.

Thanks for report :)

**Comment by mlugg** [comment]
Pretty sure everything here has been fixed so this can be closed
